const DRAGON = {
  FETCH_START: 'DRAGON_FETCH_START',
  FETCH_ERROR: 'DRAGON_FETCH_ERROR',
  FETCH_SUCCESS: 'DRAGON_FETCH_SUCCESS'
}

const GENERATION = {
  FETCH_START: 'GENERATION_FETCH_START',
  FETCH_ERROR: 'GENERATION_FETCH_ERROR',
  FETCH_SUCCESS: 'GENERATION_FETCH_SUCCESS'
}

const ACCOUNT = {
  FETCH_START: 'ACCOUNT_FETCH_START',
  FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
  FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
  FETCH_SUCCESS_LOGOUT: 'ACCOUNT_FETCH_SUCCESS_LOGOUT'
}

const ACCOUNT_DRAGONS = {
  FETCH_START: 'ACCOUNT_DRAGONS_FETCH_START',
  FETCH_ERROR: 'ACCOUNT_DRAGONS_FETCH_ERROR',
  FETCH_SUCCESS: 'ACCOUNT_DRAGONS_FETCH_SUCCESS'
}

const ACCOUNT_INFO = {
  FETCH_START: 'ACCOUNT_INFO_FETCH_START',
  FETCH_ERROR: 'ACCOUNT_INFO_FETCH_ERROR',
  FETCH_SUCCESS: 'ACCOUNT_INFO_FETCH_SUCCESS'
}

const PUBLIC_DRAGONS = {
  FETCH_START: 'PUBLIC_DRAGONS_FETCH_START',
  FETCH_ERROR: 'PUBLIC_DRAGONS_FETCH_ERROR',
  FETCH_SUCCESS: 'PUBLIC_DRAGONS_FETCH_SUCCESS'
}

export {
  ACCOUNT,
  DRAGON,
  GENERATION,
  ACCOUNT_DRAGONS,
  ACCOUNT_INFO,
  PUBLIC_DRAGONS
}
